// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: adapters.rs

use anyhow::{Context, Result};
use roxmltree::Document;
use std::collections::HashMap;
use std::io::{Cursor, Read};
use zip::ZipArchive;

// ── Namespace constants ──────────────────────────────────────────────────────
const BPMN2_NS: &str = "http://www.omg.org/spec/BPMN/20100524/MODEL";
const IFL_NS: &str = "http:///com.sap.ifl.model/Ifl.xsd";
const IFLW_PATH_PREFIX: &str = "src/main/resources/scenarioflows/integrationflow/";

// ── Data model ────────────────────────────────────────────────────────────────
#[derive(Debug, Clone, PartialEq)]
pub enum AdapterDirection {
    Sender,
    Receiver,
}

// #[derive(Debug)]
// pub struct ExceptionSubProcessInfo {
//     pub has_exception_subprocess: bool,
//     pub names: Vec<String>,
// }

// impl std::fmt::Display for ExceptionSubProcessInfo {
//     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
//         if self.has_exception_subprocess {
//             write!(f, "Yes — [{}]", self.names.join(", "))
//         } else {
//             write!(f, "No")
//         }
//     }
// }

impl std::fmt::Display for AdapterDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AdapterDirection::Sender => write!(f, "Sender"),
            AdapterDirection::Receiver => write!(f, "Receiver"),
        }
    }
}

#[derive(Debug)]
pub struct AdapterInfo {
    pub direction: AdapterDirection,
    pub component_type: String,
    // pub address: String,
    // pub props: HashMap<String, String>,
}

// #[derive(Debug, Tabled)]
// pub struct AdapterRow {
//     #[tabled(rename = "IFlow")]
//     pub iflow_id: String,
//     #[tabled(rename = "Direction")]
//     pub direction: String,
//     // #[tabled(rename = "Name")]
//     // pub name: String,
//     #[tabled(rename = "Adapter Type")]
//     pub component_type: String,
//     #[tabled(rename = "Address")]
//     pub address: String,
//     #[tabled(rename = "Queue Name")]
//     pub queue_name: String,
// }

// ── Public entry point ────────────────────────────────────────────────────────

// pub async fn check_exception_subprocesses(xml: &str) -> Result<ExceptionSubProcessInfo> {
//     let doc = Document::parse(xml).context("failed to parse .iflw XML")?;
//     let root = doc.root_element();

//     let names: Vec<String> = root
//         .descendants()
//         .filter(|node| {
//             // Must be a bpmn2:subProcess
//             node.tag_name().name() == "subProcess" && node.tag_name().namespace() == Some(BPMN2_NS)
//         })
//         .filter(|node| {
//             // Must have activityType = ErrorEventSubProcessTemplate
//             let props = extract_ifl_props(*node);
//             props
//                 .get("activityType")
//                 .map_or(false, |v| v == "ErrorEventSubProcessTemplate")
//         })
//         .map(|node| {
//             // Use name attribute, fall back to id if unnamed
//             node.attribute("name")
//                 .filter(|n| !n.is_empty())
//                 .or_else(|| node.attribute("id"))
//                 .unwrap_or("Unnamed")
//                 .to_string()
//         })
//         .collect();

//     Ok(ExceptionSubProcessInfo {
//         has_exception_subprocess: !names.is_empty(),
//         names,
//     })
// }

/// Download the iFlow zip, extract the .iflw file, and parse its adapters.
pub async fn fetch_iflow_adapters(
    client: &reqwest::Client,
    base_url: &str,
    token: &str,
    iflow_id: &str,
    version: &str,
) -> Result<Vec<AdapterInfo>> {
    let zip_bytes = download_iflow_zip(client, base_url, token, iflow_id, version).await?;
    let iflw_content = extract_iflw_content(zip_bytes)?;
    // parse_adapters(&iflw_content)
    parse_adapters_new(&iflw_content)
}

// ── Step 1: Download ──────────────────────────────────────────────────────────
async fn download_iflow_zip(
    client: &reqwest::Client,
    base_url: &str,
    token: &str,
    iflow_id: &str,
    version: &str,
) -> Result<Vec<u8>> {
    let url = format!(
        "{}/api/v1/IntegrationDesigntimeArtifacts(Id='{}',Version='{}')/$value",
        base_url, iflow_id, version
    );

    let response = client
        .get(&url)
        .header(reqwest::header::AUTHORIZATION, format!("Bearer {}", token))
        .header(reqwest::header::ACCEPT, "application/zip")
        .send()
        .await
        .with_context(|| format!("failed to download zip for iflow: {}", iflow_id))?;

    if !response.status().is_success() {
        anyhow::bail!(
            "iflow zip download failed for '{}': {} {}",
            iflow_id,
            response.status(),
            response.text().await.unwrap_or_default()
        );
    }

    response
        .bytes()
        .await
        .map(|b| b.to_vec())
        .with_context(|| format!("failed to read zip bytes for iflow: {}", iflow_id))
}

// ── Step 2: Extract .iflw from zip ───────────────────────────────────────────
fn extract_iflw_content(zip_bytes: Vec<u8>) -> Result<String> {
    let cursor = Cursor::new(zip_bytes);
    let mut archive = ZipArchive::new(cursor).context("failed to open zip archive")?;

    for i in 0..archive.len() {
        let mut file = archive.by_index(i).context("failed to read zip entry")?;
        let file_path = file.name().to_string();

        if file_path.starts_with(IFLW_PATH_PREFIX) && file_path.ends_with(".iflw") {
            let mut content = String::new();
            file.read_to_string(&mut content)
                .with_context(|| format!("failed to read .iflw file: {}", file_path))?;
            return Ok(content);
        }
    }

    anyhow::bail!("no .iflw file found under path: {}", IFLW_PATH_PREFIX)
}

// ── Step 3: Parse adapters from .iflw XML ────────────────────────────────────
fn parse_adapters(xml: &str) -> Result<Vec<AdapterInfo>> {
    let doc = Document::parse(xml).context("failed to parse .iflw XML")?;
    let root = doc.root_element();

    // Index all MessageFlows once — O(n) upfront, O(1) per event lookup
    let mut flow_by_target: HashMap<&str, roxmltree::Node> = HashMap::new();
    let mut flow_by_source: HashMap<&str, roxmltree::Node> = HashMap::new();

    for node in root.descendants() {
        if node.tag_name().name() == "messageFlow" && node.tag_name().namespace() == Some(BPMN2_NS)
        {
            if let Some(target) = node.attribute("targetRef") {
                flow_by_target.insert(target, node);
            }
            if let Some(source) = node.attribute("sourceRef") {
                flow_by_source.insert(source, node);
            }
        }
    }

    let mut adapters = Vec::new();

    for node in root.descendants() {
        let ns = node.tag_name().namespace();
        let tag = node.tag_name().name();

        let direction = match (tag, ns) {
            ("startEvent", Some(BPMN2_NS)) => AdapterDirection::Sender,
            ("endEvent", Some(BPMN2_NS)) => AdapterDirection::Receiver,
            _ => continue,
        };

        let is_message_event = node.children().any(|c| {
            c.tag_name().name() == "messageEventDefinition"
                && c.tag_name().namespace() == Some(BPMN2_NS)
        });

        if !is_message_event {
            continue;
        }

        let id = node.attribute("id").unwrap_or("");
        // let event_name = node.attribute("name").unwrap_or("").to_string();

        let flow_node = match direction {
            AdapterDirection::Sender => flow_by_target.get(id),
            AdapterDirection::Receiver => flow_by_source.get(id),
        };

        if let Some(flow) = flow_node {
            let props = extract_ifl_props(*flow);
            adapters.push(AdapterInfo {
                direction,
                component_type: props
                    .get("ComponentType")
                    .cloned()
                    .unwrap_or_else(|| "N/A".to_string()),
                // address: props
                //     .get("address")
                //     .cloned()
                //     .unwrap_or_else(|| "N/A".to_string()),
                // props,
            });
        }
    }

    Ok(adapters)
}

fn parse_adapters_new(xml: &str) -> Result<Vec<AdapterInfo>> {
    let doc = Document::parse(xml).context("failed to parse .iflw XML")?;
    let root = doc.root_element();

    // ── 1. Build participant-type index ───────────────────────────────────────
    // Try both namespace-qualified and local-name fallback for ifl:type
    let mut participant_type: HashMap<&str, &str> = HashMap::new();
    for node in root.descendants() {
        if node.tag_name().name() != "participant" || node.tag_name().namespace() != Some(BPMN2_NS)
        {
            continue;
        }
        let Some(id) = node.attribute("id") else {
            continue;
        };

        // Primary: namespace-qualified attribute ifl:type
        let ifl_type = node
            .attribute((IFL_NS, "type"))
            // Fallback: some parsers expose it as plain "ifl:type" local name
            .or_else(|| node.attribute("ifl:type"))
            // Last resort: read from ifl:property <key>ifl:type</key>
            .or_else(|| {
                node.descendants()
                    .find(|n| n.tag_name().name() == "key" && n.text() == Some("ifl:type"))
                    .and_then(|key_node| {
                        key_node
                            .next_sibling_element()
                            .filter(|n| n.tag_name().name() == "value")
                            .and_then(|n| n.text())
                    })
            });

        if let Some(t) = ifl_type {
            participant_type.insert(id, t);
        }
    }

    // ── 2. Walk messageFlows; deduplicate by flow id ──────────────────────────
    let mut seen_ids: std::collections::HashSet<&str> = std::collections::HashSet::new();
    let mut adapters = Vec::new();

    for node in root.descendants() {
        if node.tag_name().name() != "messageFlow" || node.tag_name().namespace() != Some(BPMN2_NS)
        {
            continue;
        }

        // Skip duplicate nodes (same flow can appear in DI section as bpmnElement ref)
        let flow_id = node.attribute("id").unwrap_or("");
        if !flow_id.is_empty() && !seen_ids.insert(flow_id) {
            continue; // already processed
        }

        let source = node.attribute("sourceRef").unwrap_or("");
        let target = node.attribute("targetRef").unwrap_or("");

        let direction = if participant_type
            .get(source)
            .map_or(false, |t| t.contains("Sender"))
        {
            AdapterDirection::Sender
        } else if participant_type
            .get(target)
            .map_or(false, |t| t.contains("Receiver"))
        // covers both "Receiver" and "Recevier"
        {
            AdapterDirection::Receiver
        } else {
            // ── Fallback: trust the ifl:property direction value ──────────────
            let props = extract_ifl_props(node);
            match props.get("direction").map(String::as_str) {
                Some("Sender") => AdapterDirection::Sender,
                Some("Receiver") => AdapterDirection::Receiver,
                _ => continue,
            }
        };

        let props = extract_ifl_props(node);
        adapters.push(AdapterInfo {
            direction,
            component_type: props
                .get("ComponentType")
                .cloned()
                .unwrap_or_else(|| "N/A".to_string()),
        });
    }

    Ok(adapters)
}

// ── ifl:property extractor ────────────────────────────────────────────────────
fn extract_ifl_props(node: roxmltree::Node) -> HashMap<String, String> {
    let mut map = HashMap::new();

    let ext = match node.children().find(|n| {
        n.tag_name().name() == "extensionElements" && n.tag_name().namespace() == Some(BPMN2_NS)
    }) {
        Some(e) => e,
        None => return map,
    };

    for prop in ext
        .children()
        .filter(|n| n.tag_name().name() == "property" && n.tag_name().namespace() == Some(IFL_NS))
    {
        let key = prop
            .children()
            .find(|n| n.tag_name().name() == "key")
            .and_then(|n| n.text())
            .unwrap_or("")
            .to_string();

        let value = prop
            .children()
            .find(|n| n.tag_name().name() == "value")
            .and_then(|n| n.text())
            .unwrap_or("")
            .to_string();

        if !key.is_empty() {
            map.insert(key, value);
        }
    }

    map
}
