// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/utils.rs

pub use crate::adapters::{AdapterDirection, fetch_iflow_adapters};

use chrono::{DateTime, Utc};
use indexmap::IndexMap;
use tabled::Tabled;

#[derive(Tabled)]
pub struct DetailRow {
    #[tabled(rename = "Field")]
    pub field: String,
    #[tabled(rename = "Value")]
    pub value: String,
}

pub fn format_timestamp(value: &str) -> String {
    if let Ok(ms) = value.parse::<i64>() {
        if let Some(dt) = DateTime::from_timestamp_millis(ms) {
            return dt.with_timezone(&Utc).format("%m-%d-%Y").to_string();
        }
    }

    if let Ok(seconds) = value.parse::<i64>() {
        if let Some(dt) = DateTime::from_timestamp(seconds, 0) {
            return dt
                .with_timezone(&Utc)
                .format("%Y-%m-%d %H:%M:%S UTC")
                .to_string();
        }
    }

    if let Ok(dt) = DateTime::parse_from_rfc3339(value) {
        return dt
            .with_timezone(&Utc)
            .format("%Y-%m-%d %H:%M:%S UTC")
            .to_string();
    }

    value.to_string()
}

pub fn summarise_adapters(types: Vec<&str>) -> String {
    let mut counts: IndexMap<&str, usize> = IndexMap::new();
    for t in types {
        *counts.entry(t).or_insert(0) += 1;
    }
    counts
        .iter()
        .map(|(t, n)| {
            if *n > 1 {
                format!("{} {}", n, t)
            } else {
                t.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}
